Add  server and 4 handlers
skosovsky/go-rest-api-homework pull request #1
Opened 2024-03-05 05:50 UTC by skosovsky

Добавлены:
- запуск сервера со списком задач (реализован таймаут, понятное название ошибок)
- 4 хендлера (получение списка задачи, получение задачи, удаление задачи, добавление задачи)

Дополнительно добавлены:
- файлы настройки проекта

2024-03-05 08:46 UTC, skosovsky commented
Меня смущает, что JSON содержит дополнительно уровень 1, 2, 3... из мапы, может быть из мапы в слайс переложить?

2024-03-05 09:06 UTC, skosovsky commented
autotests.yaml - я так понимаю лишний в репо? можно его удалить?

2024-03-05 15:01 UTC, robotomize commented
> autotests.yaml - я так понимаю лишний в репо? можно его удалить?

Тут не подскажу

2024-03-05 15:07 UTC, robotomize requested changes
Все в целом очень хорошо, но предлагаю исправить историю с удалением и двигаться дальше

2024-03-05 15:07 UTC, robotomize commented on main.go
> +		log.Println(err)
Думаю можно просто fmt.Printf() сделать так как нам не нужно хэндлить ошибку где-то следовательно и %w нам не особо нужен мы можем использовать %v

Это в принципе ко всем похожим ситуациями написал

2024-03-05 15:07 UTC, robotomize commented on main.go
> +	w.Header().Set("Content-Type", "application/json, charset=utf-8")
Тут нам не особо нужно давать контент тайп так как мы все равно отдаем только код

2024-03-05 15:07 UTC, robotomize commented on main.go
> +		err := errors.New("task not found")
Я бы вынес эту ошибку в var ErrNotFound = errors.New()

2024-03-05 15:08 UTC, robotomize commented
> Меня смущает, что JSON содержит дополнительно уровень 1, 2, 3... из мапы, может быть из мапы в слайс переложить? Хотя в рамках задачи переменная уже есть в прекоде - поэтому пока оставил так.

Я бы сделал слайс, но в задании это не принципиально, можно и готовую мапу использовать, хорошо, что задумались над этим моментов

2024-03-18 14:56 UTC, skosovsky commented
Добавлены:
- 3 варианта реализации "базы данных": map, slice, file (с сохранением изменений)
- добавлена документация by swagger (не всё работает, но и цели такой не было)
- переработан код: ошибки вынесены, для бд реализованы интерфейсы и т.п.

>> касаемо комментария: Удаление операция идемпотентная, нам в принципе не нужно проверять, существует объект или нет. Это операция относится как к методу DELETE так и к мапе, можно безопасно удалять, это улчше исправить
- это не исправлено, т.к. по ТЗ необходимо возвращать ошибку, если нет значения с таким ID

2024-03-18 15:59 UTC, skosovsky commented
Дайте пожалуйста замечаний по структуре проекта, как правильнее?

2024-03-18 17:34 UTC, skosovsky commented
Дайте пожалуйста замечаний по структуре проекта, как правильнее?

2024-03-18 19:17 UTC, robotomize approved these changes
Отличная работа! Принято!

2024-03-18 19:17 UTC, robotomize commented on internal/errs/errs.go
> +	ErrNoBD          = Error("no BD")
Я бы использовал конструкты декларации ошибок через var ErrNoAdded = errors.New("no added") чтобы их можно было хэндлить выше по коду через errors.Is(err, ErrNoAdded) {}

2024-03-18 19:17 UTC, robotomize commented on internal/errs/errs.go
> +const (
Сам файлик ошибок я бы не выносил в отдельный пакет, а держал их ближе к семантике, то ест внутри того пакета, который вы напсиали

2024-03-18 19:17 UTC, robotomize commented on internal/database/file.go
> +			err = fmt.Errorf("filed to read file: %w", err)
%w можно не использовать если вам не нужно оборачивать ошибку, в данном случае можно просто log.Printf("text: %v", err)

2024-03-18 19:17 UTC, robotomize commented on internal/database/file.go
> +func (b *BDFile) GetTasks() map[int]models.Task {
Кажется в этой функции можно сделать декларацию GetTasks() ([]models.Task, error)

2024-03-18 19:17 UTC, robotomize commented on internal/database/file.go
> +func (b *BDFile) GetTasks() map[int]models.Task {
И не делать отдельный метод для этого. Однако для поиска по id нужно будет изголятся. Ну тут простыми решениями нельзя ограничиваться если вы хотите много данных хранить в файле это все растет в БД, а там совсем другой набор решений

2024-03-18 19:17 UTC, robotomize commented on internal/database/slice.go
> +type BDSlc []models.Task
ПРоще было сделать структуру и в нем слайс. Это решило бы часть проблем

2024-03-18 19:17 UTC, robotomize commented on cmd/api/main.go
> +			return context.WithValue(context.Background(), controllers.KeyPrincipalBD, tasks)
В контексте хранить подобные вещи антипаттерн. Можно пробрасывать туда структуры, но делать это стоит аккуратно, проще сделать хээндлер как структуру и в нее передавать все зависимости типа DB

2024-03-19 12:10 UTC, skosovsky commented on internal/database/file.go
> +func (b *BDFile) GetTasks() map[int]models.Task {
Так у меня тогда у file будет несоответствие интерфейсу, в котором указаны все 5 методов.
Я понимаю что тут 2 по сути одинаковых метода, я мог бы сделать и 4 методами, но тогда мне бы пришлось возвращать интерфейс и делать приведение типов - т.к. возвращать интерфейс антипатерн - я решил просто добавить по 1 методу для возвращения списка - в мапе и в слайсе.

2024-04-03 05:03 UTC, merged